settings:
  max-tag-characters: 16
  min-tag-characters: 2

messages:
  min-tag-characters: "&cПРЕДУПРЕЖДЕНИЕ: &fМинимальное кол-во символов в названии тега - 2 символа"
  max-tag-characters: "&cПРЕДУПРЕЖДЕНИЕ: &fМаксимальное кол-во символов в названии тега - 6 символов"
  add-tag: "&6> &fВы создали новый титул %tag% &fдля этого игрока."
  no-tags: "&cПРЕДУПРЕЖДЕНИЕ: &fСписок тегов пуст."
  have-permission: "&cПРЕДУПРЕЖДЕНИЕ: &fУ Вас недостаточно прав."
  unset-tag:
    - ""
    - "&fВы успешно &aубрали &fсвой тег."
    - ""
    - "&6> &fЧтобы вернуть его обратно, воспользуйтесь списком Ваших тегов &e(/tags)"
    - ""
  set-tag:
    - ""
    - "&fВы успешно &aпоставили &fновый титул."
    - ""
    - "&6> &fЧтобы убрать титул, воспользуйтесь списком Ваших тегов &e(/tags)"
    - ""